version: "2.1"

services:
  users-db:
    container_name: users-db
    build: ./services/users/src/db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: exit 0

  locations-db:
    container_name: locations-db
    build: ./services/locations/src/db
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: exit 0

  users-data:
    build: ./services/users
    volumes:
      - ./services/users:/users
      - /users/dist
      - /users/node_modules
    healthcheck:
      test: exit 0
    command: npm install

  locations-data:
    build: ./services/locations
    volumes:
      - ./services/locations:/locations
      - /locations/dist
      - /locations/node_modules
    healthcheck:
      test: exit 0
    command: npm install

  users-transpiler:
    build: ./services/users/
    volumes_from:
      - users-data
    depends_on:
      - users-data
    command: tsc --watch

  users-service:
    build: ./services/users
    volumes_from:
      - users-data
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgres://admin:admin@users-db:5432/node_docker_api_users_dev
      - DATABASE_TEST_URL=postgres://admin:admin@users-db:5432/node_docker_api_users_test
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=changeme
    depends_on:
      - users-db
      - users-transpiler
    links:
      - users-db
    healthcheck:
      interval: 1m30s
      test: exit 0
    command: nodemon --watch dist

  locations-service:
    build: ./services/locations
    volumes_from:
      - locations-data
    ports:
      - "3004:3001"
    environment:
      - DATABASE_URL=postgres://admin:admin@locations-db:5432/node_docker_api_locations_dev
      - DATABASE_TEST_URL=postgres://admin:admin@locations-db:5432/node_docker_api_locations_test
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=changeme
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
    depends_on:
      locations-db:
        condition: service_healthy
      users-service:
        condition: service_healthy
    links:
      - locations-db
      - users-service
    command: nodemon --watch dist

  locations-transpiler:
    build: ./services/locations
    volumes_from:
      - locations-data
    depends_on:
      - locations-data
    command: tsc --watch
