version: '3'

services:

  users-db:
    container_name: users-db
    build: ./services/users/src/db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: exit 0

  users-transpiler:
    build: ./services/users/
    volumes:
      - "users:/users"
    command: tsc -w --outDir dist/ ./src/

  users-service:
    container_name: users-service
    build: ./services/users
    volumes:
      - "users:/users"
    ports:
      - '3001:3000'
    environment:
      - DATABASE_URL=postgres://admin:admin@users-db:5432/node_docker_api_users_dev
      - DATABASE_TEST_URL=postgres://admin:admin@users-db:5432/node_docker_api_users_test
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=changeme
    depends_on:
      - users-db
    links:
      - users-db
    command: nodemon dist/index.js -w dist/

  users-data:
    build: ./services/users
    volumes:
      - "users:/users"
      - /users/dist
      - /users/node_volumes
    command: npm install

  volumes:
    - users: ./services/users